name: Selenium-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - uses: browser-actions/setup-chrome@latest
      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - run: chrome --version
      - run: chromedriver --version

      - name: Build with Maven
        run: mvn -B clean test
